-- Here are my two research questions:
-- 1) Is there a correlation between the number of measures and the case fatality ratio?
-- 2) Is there a correlation between the lenght of the lockdown (enforced by most countries in the world) and the case fatality ratio?
